/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as InstallRouteImport } from './routes/install'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVisualRouteImport } from './routes/app.visual'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppCompetitorsRouteImport } from './routes/app.competitors'
import { Route as AppActionPlanRouteImport } from './routes/app.action-plan'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiVisualAuditRunRouteImport } from './routes/api/visual-audit/run'
import { Route as ApiVisualAuditGenerateFixRouteImport } from './routes/api/visual-audit/generate-fix'
import { Route as ApiVisualAuditApplyFixRouteImport } from './routes/api/visual-audit/apply-fix'
import { Route as ApiAuditsRunRouteImport } from './routes/api/audits/run'
import { Route as ApiPublicShopifyInstallRouteImport } from './routes/api/public/shopify/install'
import { Route as ApiPublicShopifyCallbackRouteImport } from './routes/api/public/shopify/callback'
import { Route as ApiPublicShopifyBillingCallbackRouteImport } from './routes/api/public/shopify/billing-callback'
import { Route as ApiPublicHooksWeeklyReportRouteImport } from './routes/api/public/hooks/weekly-report'
import { Route as ApiPublicHooksDailyVisualRouteImport } from './routes/api/public/hooks/daily-visual'
import { Route as ApiPublicHooksDailyMetricsRouteImport } from './routes/api/public/hooks/daily-metrics'
import { Route as ApiPublicHooksDailyCompetitorRouteImport } from './routes/api/public/hooks/daily-competitor'
import { Route as ApiPublicHooksDailyAuditRouteImport } from './routes/api/public/hooks/daily-audit'
import { Route as ApiPublicHooksAgencyAutofixRouteImport } from './routes/api/public/hooks/agency-autofix'
import { Route as ApiAuditsAuditIdStatusRouteImport } from './routes/api/audits/$auditId/status'
import { Route as ApiPublicShopifyWebhooksTopicRouteImport } from './routes/api/public/shopify/webhooks.$topic'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisualRoute = AppVisualRouteImport.update({
  id: '/visual',
  path: '/visual',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppActionPlanRoute = AppActionPlanRouteImport.update({
  id: '/action-plan',
  path: '/action-plan',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisualAuditRunRoute = ApiVisualAuditRunRouteImport.update({
  id: '/api/visual-audit/run',
  path: '/api/visual-audit/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisualAuditGenerateFixRoute =
  ApiVisualAuditGenerateFixRouteImport.update({
    id: '/api/visual-audit/generate-fix',
    path: '/api/visual-audit/generate-fix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVisualAuditApplyFixRoute = ApiVisualAuditApplyFixRouteImport.update({
  id: '/api/visual-audit/apply-fix',
  path: '/api/visual-audit/apply-fix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditsRunRoute = ApiAuditsRunRouteImport.update({
  id: '/api/audits/run',
  path: '/api/audits/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyInstallRoute = ApiPublicShopifyInstallRouteImport.update({
  id: '/api/public/shopify/install',
  path: '/api/public/shopify/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyCallbackRoute =
  ApiPublicShopifyCallbackRouteImport.update({
    id: '/api/public/shopify/callback',
    path: '/api/public/shopify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyBillingCallbackRoute =
  ApiPublicShopifyBillingCallbackRouteImport.update({
    id: '/api/public/shopify/billing-callback',
    path: '/api/public/shopify/billing-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyReportRoute =
  ApiPublicHooksWeeklyReportRouteImport.update({
    id: '/api/public/hooks/weekly-report',
    path: '/api/public/hooks/weekly-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyVisualRoute =
  ApiPublicHooksDailyVisualRouteImport.update({
    id: '/api/public/hooks/daily-visual',
    path: '/api/public/hooks/daily-visual',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyMetricsRoute =
  ApiPublicHooksDailyMetricsRouteImport.update({
    id: '/api/public/hooks/daily-metrics',
    path: '/api/public/hooks/daily-metrics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyCompetitorRoute =
  ApiPublicHooksDailyCompetitorRouteImport.update({
    id: '/api/public/hooks/daily-competitor',
    path: '/api/public/hooks/daily-competitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyAuditRoute =
  ApiPublicHooksDailyAuditRouteImport.update({
    id: '/api/public/hooks/daily-audit',
    path: '/api/public/hooks/daily-audit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgencyAutofixRoute =
  ApiPublicHooksAgencyAutofixRouteImport.update({
    id: '/api/public/hooks/agency-autofix',
    path: '/api/public/hooks/agency-autofix',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuditsAuditIdStatusRoute = ApiAuditsAuditIdStatusRouteImport.update({
  id: '/api/audits/$auditId/status',
  path: '/api/audits/$auditId/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyWebhooksTopicRoute =
  ApiPublicShopifyWebhooksTopicRouteImport.update({
    id: '/api/public/shopify/webhooks/$topic',
    path: '/api/public/shopify/webhooks/$topic',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/install': typeof InstallRoute
  '/pricing': typeof PricingRoute
  '/support': typeof SupportRoute
  '/api/chat': typeof ApiChatRoute
  '/app/action-plan': typeof AppActionPlanRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/visual': typeof AppVisualRoute
  '/app/': typeof AppIndexRoute
  '/api/audits/run': typeof ApiAuditsRunRoute
  '/api/visual-audit/apply-fix': typeof ApiVisualAuditApplyFixRoute
  '/api/visual-audit/generate-fix': typeof ApiVisualAuditGenerateFixRoute
  '/api/visual-audit/run': typeof ApiVisualAuditRunRoute
  '/api/audits/$auditId/status': typeof ApiAuditsAuditIdStatusRoute
  '/api/public/hooks/agency-autofix': typeof ApiPublicHooksAgencyAutofixRoute
  '/api/public/hooks/daily-audit': typeof ApiPublicHooksDailyAuditRoute
  '/api/public/hooks/daily-competitor': typeof ApiPublicHooksDailyCompetitorRoute
  '/api/public/hooks/daily-metrics': typeof ApiPublicHooksDailyMetricsRoute
  '/api/public/hooks/daily-visual': typeof ApiPublicHooksDailyVisualRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/api/public/shopify/billing-callback': typeof ApiPublicShopifyBillingCallbackRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
  '/api/public/shopify/webhooks/$topic': typeof ApiPublicShopifyWebhooksTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/install': typeof InstallRoute
  '/pricing': typeof PricingRoute
  '/support': typeof SupportRoute
  '/api/chat': typeof ApiChatRoute
  '/app/action-plan': typeof AppActionPlanRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/visual': typeof AppVisualRoute
  '/app': typeof AppIndexRoute
  '/api/audits/run': typeof ApiAuditsRunRoute
  '/api/visual-audit/apply-fix': typeof ApiVisualAuditApplyFixRoute
  '/api/visual-audit/generate-fix': typeof ApiVisualAuditGenerateFixRoute
  '/api/visual-audit/run': typeof ApiVisualAuditRunRoute
  '/api/audits/$auditId/status': typeof ApiAuditsAuditIdStatusRoute
  '/api/public/hooks/agency-autofix': typeof ApiPublicHooksAgencyAutofixRoute
  '/api/public/hooks/daily-audit': typeof ApiPublicHooksDailyAuditRoute
  '/api/public/hooks/daily-competitor': typeof ApiPublicHooksDailyCompetitorRoute
  '/api/public/hooks/daily-metrics': typeof ApiPublicHooksDailyMetricsRoute
  '/api/public/hooks/daily-visual': typeof ApiPublicHooksDailyVisualRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/api/public/shopify/billing-callback': typeof ApiPublicShopifyBillingCallbackRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
  '/api/public/shopify/webhooks/$topic': typeof ApiPublicShopifyWebhooksTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/install': typeof InstallRoute
  '/pricing': typeof PricingRoute
  '/support': typeof SupportRoute
  '/api/chat': typeof ApiChatRoute
  '/app/action-plan': typeof AppActionPlanRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/visual': typeof AppVisualRoute
  '/app/': typeof AppIndexRoute
  '/api/audits/run': typeof ApiAuditsRunRoute
  '/api/visual-audit/apply-fix': typeof ApiVisualAuditApplyFixRoute
  '/api/visual-audit/generate-fix': typeof ApiVisualAuditGenerateFixRoute
  '/api/visual-audit/run': typeof ApiVisualAuditRunRoute
  '/api/audits/$auditId/status': typeof ApiAuditsAuditIdStatusRoute
  '/api/public/hooks/agency-autofix': typeof ApiPublicHooksAgencyAutofixRoute
  '/api/public/hooks/daily-audit': typeof ApiPublicHooksDailyAuditRoute
  '/api/public/hooks/daily-competitor': typeof ApiPublicHooksDailyCompetitorRoute
  '/api/public/hooks/daily-metrics': typeof ApiPublicHooksDailyMetricsRoute
  '/api/public/hooks/daily-visual': typeof ApiPublicHooksDailyVisualRoute
  '/api/public/hooks/weekly-report': typeof ApiPublicHooksWeeklyReportRoute
  '/api/public/shopify/billing-callback': typeof ApiPublicShopifyBillingCallbackRoute
  '/api/public/shopify/callback': typeof ApiPublicShopifyCallbackRoute
  '/api/public/shopify/install': typeof ApiPublicShopifyInstallRoute
  '/api/public/shopify/webhooks/$topic': typeof ApiPublicShopifyWebhooksTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/install'
    | '/pricing'
    | '/support'
    | '/api/chat'
    | '/app/action-plan'
    | '/app/competitors'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/visual'
    | '/app/'
    | '/api/audits/run'
    | '/api/visual-audit/apply-fix'
    | '/api/visual-audit/generate-fix'
    | '/api/visual-audit/run'
    | '/api/audits/$auditId/status'
    | '/api/public/hooks/agency-autofix'
    | '/api/public/hooks/daily-audit'
    | '/api/public/hooks/daily-competitor'
    | '/api/public/hooks/daily-metrics'
    | '/api/public/hooks/daily-visual'
    | '/api/public/hooks/weekly-report'
    | '/api/public/shopify/billing-callback'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
    | '/api/public/shopify/webhooks/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/install'
    | '/pricing'
    | '/support'
    | '/api/chat'
    | '/app/action-plan'
    | '/app/competitors'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/visual'
    | '/app'
    | '/api/audits/run'
    | '/api/visual-audit/apply-fix'
    | '/api/visual-audit/generate-fix'
    | '/api/visual-audit/run'
    | '/api/audits/$auditId/status'
    | '/api/public/hooks/agency-autofix'
    | '/api/public/hooks/daily-audit'
    | '/api/public/hooks/daily-competitor'
    | '/api/public/hooks/daily-metrics'
    | '/api/public/hooks/daily-visual'
    | '/api/public/hooks/weekly-report'
    | '/api/public/shopify/billing-callback'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
    | '/api/public/shopify/webhooks/$topic'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/dashboard'
    | '/install'
    | '/pricing'
    | '/support'
    | '/api/chat'
    | '/app/action-plan'
    | '/app/competitors'
    | '/app/notifications'
    | '/app/reports'
    | '/app/settings'
    | '/app/visual'
    | '/app/'
    | '/api/audits/run'
    | '/api/visual-audit/apply-fix'
    | '/api/visual-audit/generate-fix'
    | '/api/visual-audit/run'
    | '/api/audits/$auditId/status'
    | '/api/public/hooks/agency-autofix'
    | '/api/public/hooks/daily-audit'
    | '/api/public/hooks/daily-competitor'
    | '/api/public/hooks/daily-metrics'
    | '/api/public/hooks/daily-visual'
    | '/api/public/hooks/weekly-report'
    | '/api/public/shopify/billing-callback'
    | '/api/public/shopify/callback'
    | '/api/public/shopify/install'
    | '/api/public/shopify/webhooks/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  InstallRoute: typeof InstallRoute
  PricingRoute: typeof PricingRoute
  SupportRoute: typeof SupportRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiAuditsRunRoute: typeof ApiAuditsRunRoute
  ApiVisualAuditApplyFixRoute: typeof ApiVisualAuditApplyFixRoute
  ApiVisualAuditGenerateFixRoute: typeof ApiVisualAuditGenerateFixRoute
  ApiVisualAuditRunRoute: typeof ApiVisualAuditRunRoute
  ApiAuditsAuditIdStatusRoute: typeof ApiAuditsAuditIdStatusRoute
  ApiPublicHooksAgencyAutofixRoute: typeof ApiPublicHooksAgencyAutofixRoute
  ApiPublicHooksDailyAuditRoute: typeof ApiPublicHooksDailyAuditRoute
  ApiPublicHooksDailyCompetitorRoute: typeof ApiPublicHooksDailyCompetitorRoute
  ApiPublicHooksDailyMetricsRoute: typeof ApiPublicHooksDailyMetricsRoute
  ApiPublicHooksDailyVisualRoute: typeof ApiPublicHooksDailyVisualRoute
  ApiPublicHooksWeeklyReportRoute: typeof ApiPublicHooksWeeklyReportRoute
  ApiPublicShopifyBillingCallbackRoute: typeof ApiPublicShopifyBillingCallbackRoute
  ApiPublicShopifyCallbackRoute: typeof ApiPublicShopifyCallbackRoute
  ApiPublicShopifyInstallRoute: typeof ApiPublicShopifyInstallRoute
  ApiPublicShopifyWebhooksTopicRoute: typeof ApiPublicShopifyWebhooksTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visual': {
      id: '/app/visual'
      path: '/visual'
      fullPath: '/app/visual'
      preLoaderRoute: typeof AppVisualRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/action-plan': {
      id: '/app/action-plan'
      path: '/action-plan'
      fullPath: '/app/action-plan'
      preLoaderRoute: typeof AppActionPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visual-audit/run': {
      id: '/api/visual-audit/run'
      path: '/api/visual-audit/run'
      fullPath: '/api/visual-audit/run'
      preLoaderRoute: typeof ApiVisualAuditRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visual-audit/generate-fix': {
      id: '/api/visual-audit/generate-fix'
      path: '/api/visual-audit/generate-fix'
      fullPath: '/api/visual-audit/generate-fix'
      preLoaderRoute: typeof ApiVisualAuditGenerateFixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visual-audit/apply-fix': {
      id: '/api/visual-audit/apply-fix'
      path: '/api/visual-audit/apply-fix'
      fullPath: '/api/visual-audit/apply-fix'
      preLoaderRoute: typeof ApiVisualAuditApplyFixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audits/run': {
      id: '/api/audits/run'
      path: '/api/audits/run'
      fullPath: '/api/audits/run'
      preLoaderRoute: typeof ApiAuditsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/install': {
      id: '/api/public/shopify/install'
      path: '/api/public/shopify/install'
      fullPath: '/api/public/shopify/install'
      preLoaderRoute: typeof ApiPublicShopifyInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/callback': {
      id: '/api/public/shopify/callback'
      path: '/api/public/shopify/callback'
      fullPath: '/api/public/shopify/callback'
      preLoaderRoute: typeof ApiPublicShopifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/billing-callback': {
      id: '/api/public/shopify/billing-callback'
      path: '/api/public/shopify/billing-callback'
      fullPath: '/api/public/shopify/billing-callback'
      preLoaderRoute: typeof ApiPublicShopifyBillingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-report': {
      id: '/api/public/hooks/weekly-report'
      path: '/api/public/hooks/weekly-report'
      fullPath: '/api/public/hooks/weekly-report'
      preLoaderRoute: typeof ApiPublicHooksWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-visual': {
      id: '/api/public/hooks/daily-visual'
      path: '/api/public/hooks/daily-visual'
      fullPath: '/api/public/hooks/daily-visual'
      preLoaderRoute: typeof ApiPublicHooksDailyVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-metrics': {
      id: '/api/public/hooks/daily-metrics'
      path: '/api/public/hooks/daily-metrics'
      fullPath: '/api/public/hooks/daily-metrics'
      preLoaderRoute: typeof ApiPublicHooksDailyMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-competitor': {
      id: '/api/public/hooks/daily-competitor'
      path: '/api/public/hooks/daily-competitor'
      fullPath: '/api/public/hooks/daily-competitor'
      preLoaderRoute: typeof ApiPublicHooksDailyCompetitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-audit': {
      id: '/api/public/hooks/daily-audit'
      path: '/api/public/hooks/daily-audit'
      fullPath: '/api/public/hooks/daily-audit'
      preLoaderRoute: typeof ApiPublicHooksDailyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agency-autofix': {
      id: '/api/public/hooks/agency-autofix'
      path: '/api/public/hooks/agency-autofix'
      fullPath: '/api/public/hooks/agency-autofix'
      preLoaderRoute: typeof ApiPublicHooksAgencyAutofixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audits/$auditId/status': {
      id: '/api/audits/$auditId/status'
      path: '/api/audits/$auditId/status'
      fullPath: '/api/audits/$auditId/status'
      preLoaderRoute: typeof ApiAuditsAuditIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/$topic': {
      id: '/api/public/shopify/webhooks/$topic'
      path: '/api/public/shopify/webhooks/$topic'
      fullPath: '/api/public/shopify/webhooks/$topic'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppActionPlanRoute: typeof AppActionPlanRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVisualRoute: typeof AppVisualRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionPlanRoute: AppActionPlanRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVisualRoute: AppVisualRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  InstallRoute: InstallRoute,
  PricingRoute: PricingRoute,
  SupportRoute: SupportRoute,
  ApiChatRoute: ApiChatRoute,
  ApiAuditsRunRoute: ApiAuditsRunRoute,
  ApiVisualAuditApplyFixRoute: ApiVisualAuditApplyFixRoute,
  ApiVisualAuditGenerateFixRoute: ApiVisualAuditGenerateFixRoute,
  ApiVisualAuditRunRoute: ApiVisualAuditRunRoute,
  ApiAuditsAuditIdStatusRoute: ApiAuditsAuditIdStatusRoute,
  ApiPublicHooksAgencyAutofixRoute: ApiPublicHooksAgencyAutofixRoute,
  ApiPublicHooksDailyAuditRoute: ApiPublicHooksDailyAuditRoute,
  ApiPublicHooksDailyCompetitorRoute: ApiPublicHooksDailyCompetitorRoute,
  ApiPublicHooksDailyMetricsRoute: ApiPublicHooksDailyMetricsRoute,
  ApiPublicHooksDailyVisualRoute: ApiPublicHooksDailyVisualRoute,
  ApiPublicHooksWeeklyReportRoute: ApiPublicHooksWeeklyReportRoute,
  ApiPublicShopifyBillingCallbackRoute: ApiPublicShopifyBillingCallbackRoute,
  ApiPublicShopifyCallbackRoute: ApiPublicShopifyCallbackRoute,
  ApiPublicShopifyInstallRoute: ApiPublicShopifyInstallRoute,
  ApiPublicShopifyWebhooksTopicRoute: ApiPublicShopifyWebhooksTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
